[package]
name = "mokio"
version = "0.1.0"
edition = "2021"

[dependencies]
rubicon = { path = "../../rubicon" }

[features]
import-globals = ["rubicon/import-globals"]
export-globals = ["rubicon/export-globals"]
